#ifndef SNAKE_PROPERTIES_H
#define SNAKE_PROPERTIES_H

#include "libdeclare.h"

void SETTING_THE_DIRECTION();

void SETTING_THE_WALL_PASSING_STATES();

void SETTING_THE_MOVEMENTS();

void SETTING_THE_ROTATION_ANGLES();

void SETTING_THE_FLIP_STATES();

#endif // SNAKE_PROPERTIES_H
